blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from .views import ArticleListView, ArticleCreateView, ArticleDeleteView, ArticleDetailView, ArticleUpdateView


app_name = BlogConfig.name

urlpatterns = [
    path('article_list/', ArticleListView.as_view(), name='article_list'),
    path('create/', ArticleCreateView.as_view(), name='article_create'),
    path('<int:pk>/detail/', ArticleDetailView.as_view(), name='article_detail'),
    path('<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
    path('<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete')
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ContactsView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, ProductCategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('<int:pk>/product_detail/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='product_create'),
    path('<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product_list/<int:category_id>/', ProductCategoryListView.as_view(), name='category'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserProfileUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('profile/', UserProfileUpdateView.as_view(), name='profile'),
]

blog/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField (
        max_length=150,
        verbose_name='Заголовок',
        help_text='Введите заголовок статьи'
    )
    text = models.TextField(
        verbose_name='Содержание',
        help_text='Напишите статью'
    )
    photo = models.ImageField(
        verbose_name='Фотография',
        help_text='Загрузите фото',
        upload_to='blog/media',
        null=True,
        blank=True
    )
    created_at = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True
    )
    is_published = models.BooleanField(
        default=False,
        verbose_name='Опубликовать'
    )
    view_counter = models.PositiveIntegerField(
        verbose_name='Счетчик просмотров',
        help_text='Загрузите количество просмотров',
        default=0
    )

    def __str__(self):
        return f'Статья "{self.title}", статус публикации: {self.is_published}, просмотрена: {self.view_counter} раз.'

    class Meta:
        verbose_name = "статья"
        verbose_name_plural = "статьи"
        ordering = ["title",]

blog/views.py
from django.core.mail import send_mail
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from config import settings
from .models import Article


class ArticleListView(ListView):
    model = Article
    paginate_by = 16

    def get_queryset(self):
        queryset = super().get_queryset().filter(is_published=True).order_by('-created_at')
        return queryset


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_counter += 1
        self.object.save()

        if self.object.view_counter == 100:
            self.send_email()

        return self.object

    def send_email(self):
        subject = 'Поздравляем! Статья набрала 100 просмотров.'
        message = (f'Ваша статья "{self.object.title}" набрала 100 просмотров. '
                   f'Сообщество Pure life поздравляет Вас с достижением!')
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[settings.ADMIN_EMAIL],
            fail_silently=False,
        )


class ArticleCreateView(CreateView):
    model = Article
    fields = ['title', 'text', 'photo', 'is_published']
    success_url = reverse_lazy('blog:article_list')


class ArticleUpdateView(UpdateView):
    model = Article
    fields = ['title', 'text', 'photo', 'is_published']
    success_url = reverse_lazy('blog:article_list')

    def get_success_url(self):
        return reverse('blog:article_detail', args=[self.kwargs.get('pk')])


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('blog:article_list')

blog/templates/blog/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            Pure life
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'blog:article_list' %}">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

blog/templates/blog/includes/nav_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal me-2">Pure life</h5>
    <nav class="d-flex align-items-center">
        <a class="p-2 btn btn-outline-primary me-2" href="{% url 'blog:article_list' %}">Статьи</a>
        <a class="p-2 btn btn-outline-primary me-2" href="{% url 'blog:article_create' %}">Добавить статью</a>
        {% if user.is_authenticated %}
        <div class="dropdown">
            {% if user.avatar %}
            <img src="{{ user.avatar.url }}" class="dropdown-toggle rounded-circle" href="#" role="button"
                 data-bs-toggle="dropdown" aria-expanded="false" width="40" height="40" alt="Аватар">
            {% else %}
            <img src="/media/users/default_avatar.png" class="dropdown-toggle rounded-circle" href="#"
                 role="button" data-bs-toggle="dropdown" aria-expanded="false" width="40" height="40" alt="Аватар">
            {% endif %}
            <ul class="dropdown-menu dropdown-menu-end">
                <li><a class="dropdown-item" href="{% url 'users:profile' %}">Мой профиль</a></li>
                <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выход</a></li>
            </ul>
        </div>
        {% else %}
        <a class="p-2 btn btn-outline-primary me-2" href="{% url 'users:login' %}">Вход</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

blog/templates/blog/includes/pagination.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="First">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">&laquo;&laquo;</span>
            </li>
            <li class="page-item disabled">
                <span class="page-link">&laquo;</span>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active"><span class="page-link">{{ num }}</span></li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">&raquo;</span>
            </li>
            <li class="page-item disabled">
                <span class="page-link">&raquo;&raquo;</span>
            </li>
        {% endif %}
    </ul>
</nav>
{% endif %}