blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from .views import ArticleListView, ArticleCreateView, ArticleDeleteView, ArticleDetailView, ArticleUpdateView


app_name = BlogConfig.name

urlpatterns = [
    path('article_list/', ArticleListView.as_view(), name='article_list'),
    path('create/', ArticleCreateView.as_view(), name='article_create'),
    path('<int:pk>/detail/', ArticleDetailView.as_view(), name='article_detail'),
    path('<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
    path('<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete')
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ContactsView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, ProductCategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('<int:pk>/product_detail/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='product_create'),
    path('<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product_list/<int:category_id>/', ProductCategoryListView.as_view(), name='category'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserProfileUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('profile/', UserProfileUpdateView.as_view(), name='profile'),
]

catalog/models.py
from django.core.validators import FileExtensionValidator
from django.db import models

from users.models import User


class Product(models.Model):
    PUBLISHED = 'published'
    UNPUBLISHED = 'unpublished'

    PUBLICATION_STATUS_CHOICES = [
        (PUBLISHED, 'Опубликовать'),
        (UNPUBLISHED, 'На рассмотрении')
    ]

    name = models.CharField(
        max_length=100,
        verbose_name="Наименование продукта",
        help_text="Введите наименование продукта",
    )
    description = models.TextField(
        verbose_name="Описание",
        help_text="Введите описание продукта",
        null=True,
        blank=True,
    )
    image = models.ImageField(
        verbose_name="Изображение",
        help_text="Загрузите изображение",
        upload_to="catalog/media",
        null=True,
        blank=True,
        validators=[FileExtensionValidator(
            allowed_extensions=['jpeg', 'png'],
            message='Допустимы только файлы в формате JPEG или PNG'
        )]
    )
    category = models.ForeignKey(
        "Category",
        verbose_name="Категория",
        help_text="Выберите категорию",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="products",
    )
    price = models.FloatField(
        verbose_name="Цена за покупку", help_text="Введите цену за покупку продукта"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания",
        help_text="Укажите дату создания"
    )
    upload_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата последнего изменения",
        help_text="Укажите дату последнего изменения",
    )
    publication_status = models.CharField(
        max_length=15,
        choices=PUBLICATION_STATUS_CHOICES,
        default=UNPUBLISHED,
        verbose_name='Статус публикации'
    )
    owner = models.ForeignKey(
        User,
        verbose_name='владелец',
        blank=True,
        null=True,
        help_text='Укажите владельца',
        on_delete=models.SET_NULL
    )

    def __str__(self):
        return f'{self.name} относится к категории "{self.category}". Цена за единицу - {self.price}'

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        ordering = ["category", "name"]
        permissions = [
            ('can_unpublish_product', 'Can unpublish product')
        ]


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Наименование категории",
        help_text="Введите категорию товара",
    )
    description = models.TextField(
        verbose_name="Описание",
        help_text="Введите описание категории",
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"


class Contact(models.Model):
    name = models.CharField(max_length=50, verbose_name='Имя', help_text='Введите имя')
    phone = models.CharField(max_length=30, verbose_name='Телефон', help_text='Введите номер телефона')
    message = models.TextField(verbose_name='Сообщение', help_text='Введите дополнительную информацию', blank=
    True, null=True)

    def __str__(self):
        return (f'Контактные данные:\n'
                f'Имя: {self.name}\n'
                f'Телефон: {self.phone}')

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'
        ordering = ['name', ]

catalog/forms.py
from django.core.exceptions import ValidationError
from django.core.validators import validate_image_file_extension
from django.db.models import BooleanField
from django.forms import ModelForm
from .models import Product


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, ModelForm):
    unallowed = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        exclude = ('created_at', 'upload_at', 'publication_status', 'owner')

    def clean_name(self):
        name = self.cleaned_data.get('name').lower()
        if name in self.unallowed:
            raise ValidationError(f'Нельзя называть продукт словом "{name}".')
        return name

    def clean_description(self):
        description = self.cleaned_data.get('description').lower()
        for word in self.unallowed:
            if word in description:
                raise ValidationError(f'Исключите слово "{word}" из описания продукта. Это запрещенное слово.')
        return description

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price < 0:
            raise ValidationError('Цена не может быть отрицательной')
        return price

    def clean_image(self):
        image = self.cleaned_data.get('image')
        if image:
            max_size = 5 * 1024 * 1024
            if image.size > max_size:
                raise ValidationError('Максимальный размер изображения 5 МБ')
        return image


class ProductModeratorForm(ProductForm):
    class Meta:
        model = Product
        fields = ('publication_status',)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.contrib import messages
from catalog.models import Contact, Product
from .forms import ProductForm, ProductModeratorForm
from .services import get_products_in_category, get_products_from_cache


class ProductListView(ListView):
    model = Product
    paginate_by = 4

    def get_queryset(self):
        queryset = get_products_from_cache()

        if not self.request.user.is_authenticated or not self.request.user.groups.exists():
            list_products = queryset.filter(publication_status=Product.PUBLISHED)[:5]
        else:
            list_products = queryset

        for product in list_products:
            print(f'{product.name} - {product.created_at}')

        return list_products


class ProductCategoryListView(ProductListView):
    def get_queryset(self):
        queryset = super().get_queryset().model.objects.all()

        category_id = self.kwargs['category_id']
        return get_products_in_category(queryset, category_id)



class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')
    login_url = reverse_lazy('users:login')

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def get_success_url(self):
        return reverse('catalog:product_detail', args=[self.kwargs.get('pk')])

    def get_form_class(self):
        user = self.request.user
        if user.groups.filter(name='Модератор продуктов').exists():
            return ProductModeratorForm
        if user == self.object.owner:
            return ProductForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')


class ContactsView(TemplateView):
    template_name = 'catalog/contact_form.html'

    def post(self, request, *args, **kwargs):
        data = {
            'name': request.POST.get('name'),
            'phone': request.POST.get('phone'),
            'message': request.POST.get('message'),
        }
        Contact.objects.create(name=data.get('name'), phone=data.get('phone'), message=data.get('message'))
        print(f"Пользователь отправил данные:\nname: {data.get('name')}, phone: {data.get('phone')}, message: {data.get('message')}")
        messages.success(request, 'Ваше сообщение успешно отправлено!')
        return super().get(request, *args, **kwargs)

catalog/templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            FoodStore
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'blog:article_list' %}">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

catalog/templates/includes/nav_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal me-2">FoodStore</h5>
    <nav class="d-flex align-items-center">
        <div class="dropdown d-inline-block me-2">
            <a class="btn btn-outline-primary dropdown-toggle p-2" href="#" role="button" data-bs-toggle="dropdown"
               aria-expanded="false">Каталог</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'catalog:category' 1 %}">Мясо и мясопродукты</a></li>
                <li><a class="dropdown-item" href="{% url 'catalog:category' 2 %}">Овощи и фрукты</a></li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url 'catalog:product_list' %}">Новинки</a></li>
            </ul>
        </div>
        <a class="p-2 btn btn-outline-primary me-2" href="{% url 'catalog:product_create' %}">Добавить товар</a>
        <a class="p-2 btn btn-outline-primary me-2" href="{% url 'catalog:contacts' %}">Контакты</a>
        {% if user.is_authenticated %}
        <div class="dropdown">
            {% if user.avatar %}
            <img src="{{ user.avatar.url }}" class="dropdown-toggle rounded-circle" href="#" role="button"
                 data-bs-toggle="dropdown" aria-expanded="false" width="40" height="40" alt="Аватар">
            {% else %}
            <img src="/media/users/default_avatar.png" class="dropdown-toggle rounded-circle" href="#"
                 role="button" data-bs-toggle="dropdown" aria-expanded="false" width="40" height="40" alt="Аватар">
            {% endif %}
            <ul class="dropdown-menu dropdown-menu-end">
                <li><a class="dropdown-item" href="{% url 'users:profile' %}">Мой профиль</a></li>
                <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выход</a></li>
            </ul>
        </div>
        {% else %}
        <a class="p-2 btn btn-outline-primary me-2" href="{% url 'users:login' %}">Вход</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>